### ISSUE TITLE
Installation process in readme.md doesn't work for non-functional testing

### ISSUE THREAD

**Issue by PabloReyes** [Codeception/YiiBridge#2]
Documentation says you need to place 

``` php
require_once __DIR__.'/../_data/YiiBridge/yiit.php';
```

in tests/functional/_bootstrap.php, but https://github.com/Codeception/Codeception/blob/master/src/Codeception/Module/Yii1.php#L119 doesn't check if we are trying to launch any other kind of test that is not functional, so it always throw the exception when trying to run unit testing for example.

A solution would be to include yiit.php in /test/_bootstrap.php:

``` php
require_once __DIR__.'/_data/YiiBridge/yiit.php';
```

**Comment by DavertMik** [comment]
Good point. Thanks
